
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Genelou
 */
public class ReadFiles extends javax.swing.JDialog {
    private ObjectInputStream input;
    /**
     * Creates new form ReadFiles
     */
    public ReadFiles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openButton = new javax.swing.JButton();
        nextRecordButton = new javax.swing.JButton();
        accountNumLabel = new javax.swing.JLabel();
        accountNumField = new javax.swing.JTextField();
        fnameLabel = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        mnameLabel = new javax.swing.JLabel();
        mnameField = new javax.swing.JTextField();
        lnameLabel = new javax.swing.JLabel();
        lnameField = new javax.swing.JTextField();
        balLabel = new javax.swing.JLabel();
        balField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 2, 2));

        openButton.setText("Open File");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        getContentPane().add(openButton);

        nextRecordButton.setText("Next Record");
        nextRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRecordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextRecordButton);

        accountNumLabel.setText("Account Number:");
        getContentPane().add(accountNumLabel);

        accountNumField.setEditable(false);
        getContentPane().add(accountNumField);

        fnameLabel.setText("First Name:");
        getContentPane().add(fnameLabel);

        fnameField.setEditable(false);
        getContentPane().add(fnameField);

        mnameLabel.setText("Middle Name:");
        getContentPane().add(mnameLabel);

        mnameField.setEditable(false);
        mnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(mnameField);

        lnameLabel.setText("Last Name:");
        getContentPane().add(lnameLabel);

        lnameField.setEditable(false);
        lnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lnameField);

        balLabel.setText("Account Balance:");
        getContentPane().add(balLabel);

        balField.setEditable(false);
        getContentPane().add(balField);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameFieldActionPerformed

    private void lnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameFieldActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        // TODO add your handling code here:
        openFile();
    }//GEN-LAST:event_openButtonActionPerformed

    private void nextRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRecordButtonActionPerformed
        // TODO add your handling code here:
        readRecord();
    }//GEN-LAST:event_nextRecordButtonActionPerformed

 // read record from file
 public void readRecord()
 {
 AccountRecord record;

 // input the values from the file
 try {
 record = ( AccountRecord ) input.readObject();

 // create array of Strings to display in GUI
 //String values[] = { String.valueOf( record.getAccount() ), record.getFname(), record.getMname(), record.getLname(), String.valueOf( record.getBalance() ) };

 // display record contents

accountNumField.setText(String.valueOf(record.getAccount()));
fnameField.setText(record.getFname());
mnameField.setText(record.getMname());
lnameField.setText(record.getLname());
balField.setText(String.valueOf(record.getBalance()));

 }

 // display message when end-of-file reached
 catch ( EOFException endOfFileException ) {
 nextRecordButton.setEnabled( false );

 JOptionPane.showMessageDialog( this, "No more records in file", "End of File", JOptionPane.ERROR_MESSAGE );
 
 }

 // display error message if cannot read object
 // because class not found
 catch ( ClassNotFoundException classNotFoundException ) {
 JOptionPane.showMessageDialog( this, "Unable to create object", "Class Not Found", JOptionPane.ERROR_MESSAGE );
 }

 // display error message if cannot read
 // due to problem with file
 catch ( IOException ioException ) {
 JOptionPane.showMessageDialog( this, "Error during read from file", "Read Error", JOptionPane.ERROR_MESSAGE );
 }
 }
    
 // enable user to select file to open
 private void openFile()
 {
 // display file dialog so user can select file to open
 JFileChooser fileChooser = new JFileChooser();
 fileChooser.setFileSelectionMode(
 JFileChooser.FILES_ONLY );

 int result = fileChooser.showOpenDialog( this );

 // if user clicked Cancel button on dialog, return
 if ( result == JFileChooser.CANCEL_OPTION )
 return;

 // obtain selected file
 File fileName = fileChooser.getSelectedFile();

 // display error if file name invalid
 if ( fileName == null ||
 fileName.getName().equals( "" ) )
 JOptionPane.showMessageDialog( this, "Invalid File Name", "Invalid File Name", JOptionPane.ERROR_MESSAGE );

 else {

 // open file
 try {
 input = new ObjectInputStream(
 new FileInputStream( fileName ) );

 openButton.setEnabled( false );
 nextRecordButton.setEnabled( true );
 }

 // process exceptions opening file
 catch ( IOException ioException ) { JOptionPane.showMessageDialog( this, "Error Opening File", "Error", JOptionPane.ERROR_MESSAGE );
}

 } // end else

 } // end method openFile 
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                ReadFiles dialog = new ReadFiles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumField;
    private javax.swing.JLabel accountNumLabel;
    private javax.swing.JTextField balField;
    private javax.swing.JLabel balLabel;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField lnameField;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField mnameField;
    private javax.swing.JLabel mnameLabel;
    private javax.swing.JButton nextRecordButton;
    private javax.swing.JButton openButton;
    // End of variables declaration//GEN-END:variables
}
